env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[43b02224b01cd25462197e0cb435a9adc1311fb91d92827740c8038bfab54de1c3d1c0c6074c1c3fd0a677be6777130e]"

task:
    name: posp
    timeout_in: 120m
    container:
      image: inok2341/builder:latest
      cpu: 8
      memory: 32G      

    rclone_setup_script:
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
    download_ccache_background_script:
      - df -h && free -h && nproc && cat /etc/os* && env
      - rclone copy hysteria:posp/ccache.tar.gz /tmp -P
      - cd /tmp
      - time tar xf ccache.tar.gz
      - rm -rf ccache.tar.gz
      - mkdir -p /tmp/rom
      - cd /tmp/rom
    monitor_background_script:
      - ./monitor
    building_script:
      - ./build
    compress_ccache_script:    
      - ./upload
