#!/bin/bash


cd /tmp


com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1

# rclone_setup_script
mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf


cd /tmp
time rclone copy /tmp/rom/out/target/product/juice/potato*.zip ryuki:juice -P

cd /tmp

time rclone copy ccache.tar.gz ryuki:posp -P
